openapi: 3.0.4
info:
  title: MendLife
  description: MendLife is app for management personal tasks and to do lists.
  termsOfService: https://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: https://api.unira.ac.id
paths:
  /login:
    post:
      parameters:
        - in: body
          name: username
          schema:
            type: string
            required: true
            description: The user name for login
        - in: body
          name: password
          schema:
            type: string
            required: true
            description: The password for login in clear text